name: demoapp
description: A demo Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans_light.ttf
          weight: 300
        - asset: assets/fonts/opensans_regular.ttf
          weight: 400
        - asset: assets/fonts/opensans_bold.ttf
          weight: 700
        - asset: assets/fonts/opensans_italic.ttf
          style: italic